version: '2'
services:
  app:
    build: ./app
    command: sh -c "fresh"
    volumes:
      - ./app:/go/app
    ports:
      - "8081:8081"

  frontend:
    image: node:13.8.0-alpine3.10
    command: sh -c "npx yarn && yarn serve"
    working_dir: /src
    volumes:
      - ./frontend:/src
    ports:
      - "8080:8080"
